version: '3.8'

services:
  web:
    build: .
    container_name: secondbrain-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/secondbrain
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: secondbrain-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
